### ISSUE TITLE
[ADD] purchase_backorder

### ISSUE THREAD

**Issue by max3903** [OCA/purchase-reporting#28]
This module adds the ability to view UIGR and Backordered products on Purchase Oders. The quantity and the value of both UIGR and Backordered products is computed for purcahse order lines and then aggregated for display on the parent purchase order.

# Usage

* Go to Purchase > Purchase > Backorders. This will display a tree view of all purchase order lines with their UIGR and Backorder information as well as the last date received and the last date billed
* Select one or more items in the tree view
* Go to the Print menu
* Select PO Backorder Report to print a report of the selected items.

**Comment by pedrobaeza** [comment]
What is UIGR? And the definition of backordered products?

**Comment by max3903** [comment]
Ping @serenacyr

**Comment by max3903** [comment]
> What is UIGR? And the definition of backordered products?

UIGR = Un-Invoiced Goods Received

Backordered products = Products on the backorder of a receipt. Products you haven't received from a partially received purchase order.

**Comment by pedrobaeza** [comment]
OK, thanks for the explanation. They can be deducted from current data. Backordered qty = qty ordered - qty received, and UIGR is a bit more complicated, but not too much. I would bet for putting in blue like in sales pending lines to invoice, and maybe have a button for being clicked for having the extended quantity info.
